apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: mini-account-management-hpa
  namespace: mini
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mini-account-management

  minReplicas: 2
  maxReplicas: 10

  metrics:
    - type: Resource

      resource:
        name: cpu

        target:
          type: Utilization
          averageUtilization: 70